---
info:
  description: Training configuration repo

---

spring:
  profiles: cloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:ifoundit@eureka-sg.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
